# This is a basic workflow to help you get started with Actions

name: Create Issue Branch

on:
  # The issue.opened event below is only needed for the "immediate" mode.
  # The issue.assigned event below is only needed for the default ("auto") mode.
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Branch Name
        run: ${{ steps.Create_Issue_Branch.outputs.branchName }}
